### ISSUE TITLE
管理后台设计bug

### ISSUE THREAD

**Issue by cong-long** [martinzhou2015/SRCMS#10]
复现过程：
1. 注册用户test
2. test用户提交漏洞A，B，C，D
3. admin用户登录后台删除test用户
4. 漏洞A，B，C，D 依然保留在post表中，但是管理后台无法查看这些历史漏洞了。
期望：
只要曾经提交过的漏洞，无论提交者是否还存在这个平台，历史漏洞信息都应该能在管理后台查看。

**Comment by martinzhou2015** [comment]
您好，十分感谢您的反馈！我已经将问题记录，并将尽快确认并推送相关解决方案。感谢您对SRCMS的支持！

祝好。

**Comment by martinzhou2015** [comment]
您好，

感谢您反馈问题，目前针对此问题的修复方案如下：

在后台使用“删除前台用户”的功能时，账户将被立即禁用，用户名将会被重置为“[已删除]”，但用户的个人资料页面仍将保留。但其相关信息将会被设置为“[已删除]”

不知您觉得这个方案如何？盼回复。如果方便的话，也可以添加我的QQ：1009465756，与我联系。谢谢

Martin

**Comment by martinzhou2015** [comment]
您好，

该问题已经通过以下思路解决：

删除用户以后，用户报告仍然留存，但是用户名将会被重置为[已删除]，前后台均如此显示。请您对此项问题的解决进行复查！谢谢！

最新安装文件：https://github.com/martinzhou2015/SRCMS/commit/c3e99b9a18f9418e97b33e578ae856cd77495ee5

Martin
