### ISSUE TITLE
admin.php页面Admin无法登陆

### ISSUE THREAD

**Issue by SuPerCxyz** [martinzhou2015/SRCMS#15]
大佬   admin.php页面用提供的Admin/Admin用户名密码无法登陆啊！！！

**Comment by martinzhou2015** [comment]
您好，

欢迎咨询，请问您的数据库配置是怎么样的？请您尝试使用
admin / admin
进行登录

**Comment by SuPerCxyz** [comment]
谢谢了  刚在数据库里面找到加密后的密码用md5计算出来了！！！
