### ISSUE TITLE
账户中心/更新个人信息失败

### ISSUE THREAD

**Issue by r00tuser111** [martinzhou2015/SRCMS#16]
更新个人信息，提交任何内容都提示非法请求

**Comment by martinzhou2015** [comment]
您好，
感谢您的反馈，请问是否方便添加我的QQ，提供更多详细信息？

Martin

**Comment by r00tuser111** [comment]
已经加你了，很抱歉之前没有把图片发上来。

补图。。。
![11](https://user-images.githubusercontent.com/22544959/30577622-1632af4e-9d42-11e7-999e-70614339e1d5.png)

![22](https://user-images.githubusercontent.com/22544959/30577625-1a6e483e-9d42-11e7-89b0-4a84a65a63d2.png)

**Comment by martinzhou2015** [comment]
通过排查，该问题已通过清空Rumtime目录解决，此issue关闭。
