### ISSUE TITLE
admin 账号更新信息有错误提示

### ISSUE THREAD

**Issue by jozxing** [martinzhou2015/SRCMS#17]
>.<
Too few arguments to function I(), 0 passed in /Applications/XAMPP/xamppfiles/htdocs/Application/Admin/Controller/SettingController.class.php on line 41 and at least 1 expected
错误位置

FILE: /Applications/XAMPP/xamppfiles/htdocs/ThinkPHP/Common/functions.php 　LINE: 271

TRACE

#0 /Applications/XAMPP/xamppfiles/htdocs/Application/Admin/Controller/SettingController.class.php(41): I()
#1 [internal function]: Admin\Controller\SettingController->update()
#2 /Applications/XAMPP/xamppfiles/htdocs/ThinkPHP/Library/Think/App.class.php(173): ReflectionMethod->invoke(Object(Admin\Controller\SettingController))

**Comment by martinzhou2015** [comment]
您好，

感谢您的反馈，方便添加我的QQ定位一下问题吗：1009465756

Martin

**Comment by martinzhou2015** [comment]
感谢您的报告，目前已经定位了问题，是使用的PHP版本过高导致的。SRCMS将会在之后的迭代更新中，优化对高版本PHP的兼容性。再次感谢您的报告！

Martin
