### ISSUE TITLE
srcms普通用户权限

### ISSUE THREAD

**Issue by wcy5888** [martinzhou2015/SRCMS#18]
普通用户不能更改自己的信息，报出的错误是非法请求

**Comment by martinzhou2015** [comment]
您好，
感谢您的反馈。该问题可能是由于目前SRCMS V2系列使用的ThinkPHP 3.2.3与PHP5.6及以上版本不兼容导致的。

您可以通过以下方式进行排查：
1. 安装PHP5.5版本
2. 清空Application目录下Runtime缓存文件

以上信息希望能够帮助到您，如有问题还请继续咨询。

Martin
