### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by zhoufjr** [martinzhou2015/SRCMS#23]
Too few arguments to function I(), 0 passed in /usr/local/nginx/html/Application/User/Controller/InfoController.class.php on line 29 and at least 1 expected
这是什么情况，提交更新普通用户信息的时候，提示这个问题，求解答

**Comment by martinzhou2015** [comment]
Hi，抱歉迟了。是TP内核版本更新后产生的BUG。可以通过批量替换I()为I('post.')来解决。近期，SRCMS已经合并入腾讯xSRC维护，您也可以通过升级到xSRC解决此处问题。

**Comment by martinzhou2015** [comment]
关闭此单缺陷，如上述解决方案无法解决问题，可重新打开issue
