### ISSUE TITLE
生成工单 不正确

### ISSUE THREAD

**Issue by duolaaa** [martinzhou2015/SRCMS#3]
在测试的时候发现生成工单根据session_id查询不正确，具体表现在查询A工单可能得到B工单的内容。是个bug？

**Comment by martinzhou2015** [comment]
您好，抱歉回复晚了。这是一个已知问题，会在近期的一次更新中修复。感谢咨询。

**Comment by martinzhou2015** [comment]
您好，V1.7新版本已经解决了该问题：https://github.com/martinzhou2015/SRCMS，请您下载最新版本，感谢您提出完善建议！
