### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by is1and** [martinzhou2015/SRCMS#5]
\Admin\Controller\ManagerController.class.php , line 29,  "$model = M('member')->where($where);"  , 'member' should be 'manager'. : )

**Comment by martinzhou2015** [comment]
Thank you so much! This issue is now under investigation.

**Comment by is1and** [comment]
/Application/Admin/Controller/CategoryController.class.php

line 32

$Page may be undefined.

**Comment by martinzhou2015** [comment]
The bug has been confirmed. Thanks again. This bug is fixed in Version 1.9 ( 2016/12/24)

**Comment by martinzhou2015** [comment]
The Version 1.9 could be downloaded from the origin below now:
https://github.com/CNSISMO/SRCMS/
Thanks again! ;-）
