### ISSUE TITLE
后台更改网站相关配置时显示配置更新失败

### ISSUE THREAD

**Issue by AGLcaicai** [martinzhou2015/SRCMS#8]
后台更改网站相关配置时显示配置更新失败，但是数据库中的信息已经更改，前台的却没有更改

**Comment by martinzhou2015** [comment]
您好，

感谢您提供相关反馈，这项问题属于已知的功能不足，SRCMS V2社区开发版目前尚未完全放开通过网站后台修改前台相关显示配置的功能。

如有该项功能的需要，您可以考虑咨询采购SRCMS 商业版本，或是等待社区开发版本的后续更新。

再次感谢您的咨询。如有问题可以继续提出，谢谢！

Martin

**Comment by AGLcaicai** [comment]
商业版本如何采购？

**Comment by martinzhou2015** [comment]
您好，

新版本预计本周到下周区间发布，欢迎您持续关注。感谢您的反馈，祝您生活愉快。

此致

Martin

**Comment by martinzhou2015** [comment]
您好，此问题已经在最新发布的V2.0.1版本中修复，请您协助确认问题是否修复：
https://github.com/martinzhou2015/SRCMS/commit/8e5953cae3b4b37025c038bc15397ea0ed1fc017

祝好！
