### ISSUE TITLE
没办法上传图片

### ISSUE THREAD

**Issue by debugray** [martinzhou2015/SRCMS#9]
上传的图片路径貌似不对，windows系统

**Comment by martinzhou2015** [comment]
您好，

感谢您的反馈！此问题我尽快跟进，晚些时候给出答复。

此致

Martin

**Comment by martinzhou2015** [comment]
您好，此问题已经在最新发布的V2.0.1版本中修复，请您协助确认问题是否修复。

此外，如果您使用的是IIS服务器，请您确认是否给网站的临时目录文件开放了写入权限。

如仍存在问题，请您继续反馈。我将尽快协助您进行处理。

祝好！

**Comment by debugray** [comment]
其实我看了下是上传在非web目录../../temp下了，网页展示的时候没办法读取

**Comment by martinzhou2015** [comment]
您好，

感谢您的后续反馈和支持！如果方便的话，不知是否可以添加我的QQ深入聊一下。QQ在的代码里面有，非常感谢！

Martin

**Comment by martinzhou2015** [comment]
您好，

该问题已经在V2.2.0开发版本中修复，请您复查！如果问题仍然存在，请及时与我联系，谢谢！

https://github.com/martinzhou2015/SRCMS/commit/c3e99b9a18f9418e97b33e578ae856cd77495ee5

Martin
